#### adress of the data



camera = 'FLASH.DIAG/CAMERA/OTR9FL2XTDS/';
cam_data = 'FLASH.DIAG/CAMERA/OTR9FL2XTDS/IMAGE_EXT_ZMQ'
TDSphase='FLASH.RF/LLRF.CONTROLLER/CTRL.POLARIX/SP.PHASE';
SPECTRUM_X_CM='FLASH.DIAG/CAMERA/OTR9FL2XTDS/SPECTRUM.X.CM'
SPECTRUM_X_Mean='FLASH.DIAG/CAMERA/OTR9FL2XTDS/SPECTRUM.X.MEAN';
addr_dipol='FLASH.MAGNETS/MAGNET.ML/D4FL2XTDS/CURRENT.SP';

Charge7FL2XTDS='FLASH.DIAG/TOROID/7FL2XTDS/CHARGE.FLASH2'
Chargegun3='FLASH.DIAG/TOROID.ML/3GUN/CHARGE.FLASH2'
XTDSbpmx='FLASH.DIAG/BPM/9FL2XTDS/X.FLASH2'
XTDSbpmy='FLASH.DIAG/BPM/9FL2XTDS/Y.FLASH2'

compressionTD11='FLASH.SDIAG/BCM/FL0.DBC1.1/COMPRESSION.normalized.TD'
compressionTD12='FLASH.SDIAG/BCM/FL0.DBC1.2/COMPRESSION.normalized.TD'
compressionTD21='FLASH.SDIAG/BCM/FL0.DBC2.1/COMPRESSION.normalized.TD'
compressionTD22='FLASH.SDIAG/BCM/FL0.DBC2.2/COMPRESSION.normalized.TD'
compressionTD51='FLASH.SDIAG/BCM/FL2.SEED5.1/COMPRESSION.normalized.TD'
compressionTD52='FLASH.SDIAG/BCM/FL2.SEED5.2/COMPRESSION.normalized.TD'

BAMUBC1='FLASH.SDIAG/BAM/FL0.UBC1/ARRIVAL_TIME.relative.TD'
BAMDBC1='FLASH.SDIAG/BAM/FL0.DBC1/ARRIVAL_TIME.relative.TD'
BAMUBC2='FLASH.SDIAG/BAM/FL0.UBC2/ARRIVAL_TIME.relative.TD'
BAMDBC2='FLASH.SDIAG/BAM/FL0.DBC2/ARRIVAL_TIME.relative.TD'
BAMseed5='FLASH.SDIAG/BAM/FL2.SEED5/ARRIVAL_TIME.relative.TD'

XGM_DP='FLASH.FEL/XGM.INTENSITY/FL2.TUNNEL/INTENSITY.RAW.TRAIN'

beamenergyXTDS='FLASH.DIAG/BEAM_ENERGY_MEASUREMENT/FL2XTDS/ENERGY.ALL'
beamenergyFL2EXTR='FLASH.DIAG/BEAM_ENERGY_MEASUREMENT/FL2EXTR/ENERGY.ALL'
